### ISSUE TITLE
Studio not accessible with ILIAS ≥ 7.19

### ISSUE THREAD

**Issue by mic-men** [opencast-ilias/OpenCast#156]
**Describe the bug**
Starting with ILIAS version 7.19 the Button "Opencast Studio" does not work anymore.
It is reported that cutting of a recording fails and annotations are likely to fail.

**To Reproduce**
0. Activate OC Studio support in the plugin config.
1. Go to a series
2. Click on "Opencast Studio"
4. See empty series instead of OC Studio page

**Expected behavior**
There should be a forward to the OC Studio page in rder to do a recording.

**Log**
The plugin does only 3 requests to OC fetching info about the series and does nothing else.
There are no error messages, neither in ILIAS or OC log !

**Environment (please complete the following information):**
 - ILIAS version: 7.19
 - PHP version: 7.4.33
 - Plugin version: 5.1.0
 - Opencast version 10.13.0

**Comment by dagraf** [comment]
Thx for reporting. We can confirm this bug. @okaufman will have a look at it and fix it as soon as possible.

**Comment by chfsx** [comment]
This is due to line 787 in xoctEventGUI:
```
header('Location:' . $studio_link);
```
must be
```
$this->dic->ctrl()->redirectToURL($studio_link);
```

this has been introduced by PR for the new feature: https://github.com/opencast-ilias/OpenCast/commit/eed61309dc461a2302473b0be8547e98ae34db18

`header` must not be used directly in ILIAS. There are several other thing I think we should change such as `opencaststudio` as method name which should be something link `redirectToOpencastStudio`.

**Comment by dagraf** [comment]
After pulling https://github.com/opencast-ilias/OpenCast/pull/159 the bug does not exist anymore. I therefore close this ticket.

@mic-men: Feel free to reopen it if your tests are not successfull.
