### ISSUE TITLE
Uploads from ILIAS should be able to be stopped

### ISSUE THREAD

**Issue by ebbertd** [opencast-ilias/OpenCast#20]
**Current situation**

When a video is in upload, there is no way to cancel this upload.

**Desired implementation**

An option to cancel an upload is added.

**Comment by reiferschris** [comment]
With the new implementation of the chunk upload it is possible to pick another file before uploading. Though this is probably not what the intention of this issue was.

A proper cancel button for the upload form apparently is not possible due to constraints of the underlying form in ilias. See this comment here https://github.com/opencast-ilias/OpenCast/pull/66#issuecomment-1219528316 

I will close this issue for now. It can be reopened if ilias allows a second button in the UI form..
