### ISSUE TITLE
The status of "Publish Series on VIDEOPORTAL" does not get saved

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#212]
**Describe the bug**
If a course administrator activates the setting "Publish Series on VIDEOPORTAL", the chosen option does not get saved after clicking on 'Save'. The roles that get sent to Opencast are correct. But the setting "Publish Series on VIDEOPORTAL" gets shown as not activated. I assume that instead of saving and showing what was set, after hitting save the default template gets shown.

**To Reproduce**
1. In the plugin configuration: Have some templates configured and set one of them as "Default Template"
2. Open a series ane go to the tab 'Settings'
3. Activate the option 'Publish Series on Tobira', choose one of the configured permissions and click on 'Save'
4. See error: The option "Publish Series on VIDEOPORTAL' is NOT activated.

**Expected behavior**
The chosen option should not get lost when clicking on "Save".

**Environment (please complete the following information):**
 - ILIAS version: v7.24 2023-07-20
 - PHP version: PHP 7.4.3
 - Plugin version: 5.3.0
 - Opencast version: 13
 - Browser: Firefox

**Additional context**
I assume that the bug exists since merging the PR https://github.com/opencast-ilias/OpenCast/pull/186. Therefore, @chfsx could you please have a look at this issue?

**Comment by chfsx** [comment]
The feature seems to me to be difficult to understand by design, I may need more information here:

this is implemented (and works) in such a way that saving works if the following circumstances apply:

- at least one additional permission template has been created
- the default template cannot be selected and is not displayed in the form
- the additional (and selectable) template must have READ and WRITE activated, otherwise it will not be saved in the form

i can't say why this is the case, but it was already the case before. maybe we need to look at the feature together so that i understand it completely and why it has been implemented this way so far.

**Comment by dagraf** [comment]
Thanks for having looked into it. I was aware of the first two bullet points and have some reasons I'm happy to explain in a short meeting (see message in Element/Matrix). Maybe there, we could also come up with solution which is more reasonable or easier to understand.

The third bullet point may cause the problem. In our template the additional templates only have READ activated, WRITE is not activated. So maybe saving the form independent of the status of READ and WRITE would be the solution. Let's discuss this in a short meeting.

**Comment by dagraf** [comment]
@chfsx: See this https://github.com/opencast-ilias/OpenCast/issues/153 for more information about the feature.

**Comment by chfsx** [comment]
we remove the `the additional (and selectable) template must have READ and WRITE activated, otherwise it will not be saved in the form` implementation which makes no sense at all.
