### ISSUE TITLE
Release_8: Upload leads to error when clicking on "Upload Event" in tab "Content"

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#282]
**Describe the bug**
When I am in the tab "Content" and click on the button "Upload event" the following error appears (see also screenshot).

_Access level to ILIAS\UI\Implementation\Component\Input\Field\ChunkedFile::isClientSideValueOk() must be public (as in class ILIAS\UI\Implementation\Component\Input\Field\File)_

**To Reproduce**
1. Go to tab 'Content'
2. Click on 'Upload Event'
3. See error

**Expected behavior**
The upload form should be offered. 

**Screenshots**
<img width="1298" alt="Bildschirmfoto 2024-05-07 um 10 42 24" src="https://github.com/opencast-ilias/OpenCast/assets/15246287/3c7192fe-8af1-450b-bb03-5a94865aa6a6">

**Environment (please complete the following information):**
 - ILIAS version: v8.10 2024-03-19
 - Plugin version: 8.0.3
 - Opencast version: 15
 - Browser: Firefox

**Comment by chfsx** [comment]
the problem is new because a method has changed in the ILIAS core within a major release. for us, this means that we cannot fix this per se. because if we adjust the method in the plugin now, the plugin will only work with ILIAS 8.11, but not with 8.10 (more precisely, there is exactly one version in between where the method changes).

I will provide more detailed information in today's meeting

**Comment by dagraf** [comment]
Release of 8.11 in week of 13.5.2024

**Comment by dagraf** [comment]
Fixed for ILIAS 8.12 and higher with new version of the plugin (v8.0.4). More information: https://groups.google.com/a/opencast.org/g/lms/c/xj31oGwvqnQ/m/Guj9FenaAQAJ
