### ISSUE TITLE
Misspelled Opencast

### ISSUE THREAD

**Issue by lkiesow** [opencast-ilias/OpenCast#30]
Can we change the repository name? Opencast is misspelled. It's not written with a capitalized `C`.

**Comment by mtneug** [comment]
@ebbertd can you comment on that?

**Comment by ebbertd** [comment]
First, I totally agree with the issue and would also like to see this changed.

As for actually changing it. As far as I know this would break the installation of current users after an update as ILIAS expected the name to stay the same. I hope @Amstutz can explain this better.

**Comment by okaufman** [comment]
Already existing installations would need to change the name of their folder under plugins/Services/Repository/RepositoryObject/OpenCast manually, because a simple "git pull" will not update the name of the folder.

If we change the name of the repository, we also have to change the spelling of the classnames in the classes-folder.

**Comment by mtneug** [comment]
There is already a PR for this in one of the upstream repos.

**Comment by Amstutz** [comment]
I think we have bigger fish to fry, atm. I see much more pain than gain here. Note that also classes need to be renamed. 

Note that this is not visible to end users, since we adapt the name through language variables. If anybody is willing to write a PR, which covers all necessary refactorings in all the code. We could test it. I close this. Please don't hesitate to reopen if we find a volunteer we could assign this to.

**Comment by ebbertd** [comment]
I created a PR for this. See #31

**Comment by dagraf** [comment]
We decided as community (some time ago) to not change the name since it too much ressources would be needed with very little gain. Therefore, I close this issue.
