### ISSUE TITLE
Incorrect start date when creating event with manually uploaded subtitle file

### ISSUE THREAD

**Issue by snoesberger** [opencast-ilias/OpenCast#350]
**Describe the bug**
Opencast events created in ILIAS with manually uploaded subtitles have an incorrect start date/time. Instead of the current date/time, the start date/time of the new event is the current time +2h. For events without subtitles, the start date/time is set correctly.

**To Reproduce**
1. Go to an Opencast series in ILIAS
2. Click on 'Upload Event', add a new event with a subtitle file and publish it directly
3. The start date of the new event is the current time +2h

**Expected behavior**
The start date/time of uploaded events with subtitles should be the creation date/time.

**Environment (please complete the following information):**
 - ILIAS version: v8.14 2024-08-13
 - Plugin version: 8.1.4
 - Opencast version: 15

**Additional context**
The same problem applies if you upload a thumbnail instead of subtitles (feature introduced by https://github.com/opencast-ilias/OpenCast/pull/305).

**Comment by dagraf** [comment]
@ferishili: Since this issue is connected with a PR you created can you please have a look at this issue? Thx.

**Comment by ferishili** [comment]
According to my findings, both issues are related to the upload via **_ingest_**, and because, subtitle and thumbnail upload forcefully use ingest upload in the background, therefore it appears so that it is the subtitle/thumbnail upload problem.
To prove that, you could also switch the upload mechanism to ingest in the configurations and perform an upload **without** subtitle, and the result will also be faulty both for startDate and ACL.
with that being said, I am starting the fix right away.
