### ISSUE TITLE
Activating the option 'Set permissions for an Event' does NOT automatically show the column 'Owner'

### ISSUE THREAD

**Issue by dagraf** [opencast-ilias/OpenCast#91]
**Describe the bug**
When an admin activates the option 'Set permissions for an Event' and navigates back to the tab 'Content', the column 'Owner' is still not shown but must be activated via the button "Columns".

**To Reproduce**
1. As admin: Open a series with several published videos
2. As admin: Activate the option 'Set permissions for an Event'
3. As admin or user: Open the tab 'Content' of this series and see that you are not automatically shown the column 'Owner'.

**Expected behavior**
When the option 'Set permissions for an Event' is activated back in the tab 'Content', the column 'Owner' should by default get activated and be shown to all admins and users.

**Environment (please complete the following information):**
- ILIAS version: v7.11 2022-06-29
- Plugin version: 5.0.0
- Browser: Firefox

**Comment by chfsx** [comment]
@dagraf Did that work in the past? Because I don't think it can, or only partially, unless you're really hacking around here. 

The old table service saves the columns displayed per table per user. You can start the table with a certain number of columns initially, but when the users come back later, it remains the same for the stored values. therefore, switching the setting would probably cause the aplte owner to be displayed to new users (i.e. those accessing the series for the first time), but the aplte would probably not be displayed to the user who changed the setting.

just before we investigate too deeply into whether this is possible: did it work in the past? :-)

**Comment by dagraf** [comment]
@chfsx: Yes, it did work in the past. The details of the solution I do not know. We just tested the workflow: create a series with 'Set permissions for an Event' activated > control if column 'Owner' is shown

What do you (and maybe others) think about the following alternativ solution:
When 'Set permissions for an Event' is activated a message gets shown in the tab 'Content' which informs users and admins (i) about this and (ii) where they can activate the row 'Owner' to check who owns which videos.

**Comment by dagraf** [comment]
@chfsx: Please analyze how the older versions of the plugin (i.e., 3.7.3) solved this issue.

**Comment by Amstutz** [comment]
thx @chfsx for fixing in: https://github.com/opencast-ilias/OpenCast/pull/214
